version: "3"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: dockerfile
    ports: 
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - 5000:5000
    environment:
      - ACCES_TOKEN_SECRET=${ACCES_TOKEN_SECRET}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - './server:/api'
      - '/api/node_modules'
    depends_on:
      - db
  db:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data