
POST http://localhost:5000/api/users/signup
Content-Type: application/json
// sign up

{
    "username": "MrHat",
    "password": "MrHatIsTheBest"
}

###

POST  http://localhost:5000/api/users/login
Content-Type: application/json 
// login in

{
    "username": "MrHat",
    "password": "MrHatIsTheBest"
}
