GET http://localhost:5000/api/products
// Get all products

###

GET http://localhost:5000/api/products/:id
// Get product by id

###

POST http://localhost:5000/api/products
// Create new product
Content-Type: application/json

{
    "title": "Pekárna Brod Rohlík",
    "price": 2.50
}

###

PUT http://localhost:5000/api/products/:1
// Update product by id
Content-Type: application/json

{
  "is_visible": false, 
}

###

DELETE http://localhost:5000/api/products/38
// Delete product by id
###